"""Quantitative analysis modules."""

from pension_data.quant.attribution_optimization import (
    AttributionReconciliation,
    AttributionRow,
    ConstraintDiagnostics,
    ExperimentComparison,
    OptimizationConstraints,
    OptimizationResult,
    QuantExperimentRecord,
    QuantExperimentRegistry,
    QuantExperimentRunner,
    compute_attribution,
    optimize_allocation,
    reconcile_attribution,
)
from pension_data.quant.metric_engine import (
    AggregatedMetric,
    DerivedMetricDefinition,
    DerivedMetricObservation,
    aggregate_metric_series,
    compute_derived_metrics,
    default_metric_catalog,
)
from pension_data.quant.scenarios import (
    ReproducibilityMetadata,
    ScenarioInput,
    ScenarioMode,
    ScenarioResult,
    ScenarioResultRow,
    ScenarioRunConfig,
    run_deterministic_scenario,
    run_monte_carlo_scenario,
)

__all__ = [
    "AttributionReconciliation",
    "AggregatedMetric",
    "AttributionRow",
    "ConstraintDiagnostics",
    "DerivedMetricDefinition",
    "DerivedMetricObservation",
    "ExperimentComparison",
    "OptimizationConstraints",
    "OptimizationResult",
    "QuantExperimentRecord",
    "QuantExperimentRegistry",
    "QuantExperimentRunner",
    "ReproducibilityMetadata",
    "ScenarioInput",
    "ScenarioMode",
    "ScenarioResult",
    "ScenarioResultRow",
    "ScenarioRunConfig",
    "aggregate_metric_series",
    "compute_attribution",
    "compute_derived_metrics",
    "default_metric_catalog",
    "optimize_allocation",
    "reconcile_attribution",
    "run_deterministic_scenario",
    "run_monte_carlo_scenario",
]
